loki:
  enabled: true
  persistence:
    enabled: true
    size: 5Gi
    storageClass: standard

promtail:
  enabled: true

# helm repo add grafana https://grafana.github.io/helm-charts
# helm repo update
# helm install loki grafana/loki-stack --namespace monitoring -f loki-stack-values.yaml --wait --timeout=300s
